In [11]:
import os
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *

In [12]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
- No cargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [13]:
# %matplotlib tk

In [14]:
# # Configuraciones [Acá se indica que carpetas, mensaje y tipo de mensaje se cargará] 
# carpetas = [#"//192.168.15.249/Med_2025-2026/Reportes_Edit/Reporte_1.3/2026/03. Marzo/BOT1-02-T80/DATOS"] #,
#             "//192.168.15.249/Med_2025-2026/Reportes_Edit/Reporte_1.2/2026/03. Marzo/BOT1-01-T80/DATOS"]
# tipos = ["realt"] # realt o mem # Se debe colocar un tipo por cada archivo cargado (esto es para poder comparar una localización de mem contra otra de realt)
# msg = 4
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-02\\DATOS"
fi = "16/11/2025 19:00" # Fecha inicial de todo el estudio
ff = "08/02/2026 21:00" # Fecha final de todo el estudio
dict_de_boyas = {}

### 2. OLEAJE

In [15]:
# 1.1. Cargar crudo mem unido (binario mem + telemetría mem + binario realt + telemetría realt)
nombre = "BOT1-02-T80_pkl_mem_C"
archivos_csv = "msj3_crudo_unido_mem_2025111619_2026020821.pkl"
df_pkl_crudo_mem = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)
dict_de_boyas[nombre] = df_pkl_crudo_mem # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_mem.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-16 19:00:00  0.58  1.01  3.3  73.0    36.0
1 2025-11-16 20:00:00  0.52  0.84  3.4  69.0    38.0

In [16]:
# 1.2. Cargar telemetría cruda_unida .pkl (Binario + telemetría)
nombre = "BOT1-02-T80_pkl_realt_C"
nombre_de_archivo = "msj3_crudo_unido_realt_2025111619_2026020821.pkl"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-16 19:00:00  0.58  1.01  3.3  72.9    35.9
1 2025-11-16 20:00:00  0.52  0.84  3.4  68.8    38.4

In [17]:
# # 1.2. Cargar crudo telemetría 
# nombre = "BOT1-02-T80_DAT"
# nombre_de_archivo = "BOT1-02-T80-MENSAJE4-SIG500DW-NS103971-Z0.54-REALT-20251116-20260208-RAW.dat"
# indices = crear_indices_para_crudos_dat_o_txt("realt")
# df_dat = cargar_telemetria_adcp_dat(ruta_a_carpeta, nombre_de_archivo, indices)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [18]:
# 1.3. Cargar datos validados .pkl
nombre = "BOT1-02-T80_pkl_V"
nombre_de_archivo = "msj3_validados_mem_2025111619_2026020821.pkl"
df_pkl_validados = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_validados # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_validados.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-16 19:00:00  0.58  1.01  3.3  73.0    36.0
1 2025-11-16 20:00:00  0.52  0.84  3.4  69.0    38.0

In [19]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-02-T80_NC"
nombre_de_archivo = "BOT1-02-T80-TRIAXYSG3-NS09171-Z0-MEM-20251116-20260208.nc"
df_nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-16 19:00:00  0.58  1.01  3.3  73.0    36.0
1 2025-11-16 20:00:00  0.52  0.84  3.4  69.0    38.0

In [ ]:
# 1.4.2 Cargar NETCDF de corrientes
nombre = "BOT1-02-T80_NC"
ruta_a_carpeta2 = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-03-T50\\DATOS"
nombre_de_archivo = "BOT1-03-T50-TRIAXYSG3-NS09293-Z0-REALT-20251117-20251230.nc"
df_nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta2, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

In [20]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BOT1-02-T80_pkl_mem_C', 'Hmax_BOT1-02-T80_pkl_mem_C',
       'Tp_BOT1-02-T80_pkl_mem_C', 'dir_BOT1-02-T80_pkl_mem_C',
       'vardir_BOT1-02-T80_pkl_mem_C', 'Hs_BOT1-02-T80_pkl_realt_C',
       'Hmax_BOT1-02-T80_pkl_realt_C', 'Tp_BOT1-02-T80_pkl_realt_C',
       'dir_BOT1-02-T80_pkl_realt_C', 'vardir_BOT1-02-T80_pkl_realt_C',
       'Hs_BOT1-02-T80_pkl_V', 'Hmax_BOT1-02-T80_pkl_V',
       'Tp_BOT1-02-T80_pkl_V', 'dir_BOT1-02-T80_pkl_V',
       'vardir_BOT1-02-T80_pkl_V', 'Hs_BOT1-02-T80_NC', 'Hmax_BOT1-02-T80_NC',
       'Tp_BOT1-02-T80_NC', 'dir_BOT1-02-T80_NC', 'vardir_BOT1-02-T80_NC'],
      dtype='object')

In [21]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)