In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. ADCP

In [6]:
# # 1.3. p1: Crudo
# nombre = "BOT1-09-T50_C"
# nombre_de_archivo = "msj4_crudo_unido_realt_2026031000_2026060623.pkl"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
# df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
# dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
# df_pkl_C.head(2)

In [7]:
# p2: Crudo validados
nombre = "BOT1-09-T50_C"
nombre_de_archivo = "msj4_crudo_unido_realt_2026031000_2026060623.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
df_pkl_V, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_V # Guardo el dataframe dentro
df_pkl_V.head(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,dir_12,rap_13,dir_13,rap_14,dir_14,rap_15,dir_15,rap_16,dir_16,temp_adcp
0,2026-03-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-10 01:00:00,0.15,12.8,0.13,343.8,0.13,312.9,0.12,317.3,0.1,...,225.0,46.34,225.0,46.34,225.0,46.34,225.0,46.34,225.0,25.39

In [8]:
# 1.4. p1. NC 1 - REALT
nombre = "BOT1-09-T50_NC"
nombre_de_archivo = "BOT1-09-T50-SIG500DW-NS104499-Z0.54-REALT-20260310-20260606.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,dir_5,rap_6,dir_6,rap_7,dir_7,rap_8,dir_8,rap_9,dir_9
0,2026-03-10 01:00:00,25.389999,0.15,12.799999,0.13,343.799988,0.13,312.899994,0.12,317.299988,0.1,319.299988,0.11,306.500000,0.14,333.100006,0.15,345.799988,0.06,342.399994
1,2026-03-10 02:00:00,25.270000,0.18,4.800000,0.12,348.199982,0.14,319.699982,0.13,311.500000,0.1,314.600006,0.11,316.799988,0.14,346.799988,0.13,351.899994,0.04,326.299988

In [9]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-09-T50_datos_word_2026031000_2026060623.xlsx", variables="corrientes")

NAM correcto

    Variable  esperados  validados  porcentaje_validados
0         AE     2135.0     2081.0             97.470726
1  Temp adcp     2135.0     2010.0             94.145199
0      rap_1     2135.0     1997.0             93.536300
1      rap_2     2135.0     2007.0             94.004684
2      rap_3     2135.0     2004.0             93.864169
3      rap_4     2135.0     2008.0             94.051522
4      rap_5     2135.0     2006.0             93.957845
5      rap_6     2135.0     2005.0             93.911007
6      rap_7     2135.0     2003.0             93.817330
7      rap_8     2135.0     2001.0             93.723653
8      rap_9     2135.0     1997.0             93.536300

In [10]:
dict_de_boyas.keys()

dict_keys(['BOT1-09-T50_C', 'BOT1-09-T50_NC'])

In [11]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BOT1-09-T50_C', 'dir_1_BOT1-09-T50_C',
       'rap_2_BOT1-09-T50_C', 'dir_2_BOT1-09-T50_C', 'rap_3_BOT1-09-T50_C',
       'dir_3_BOT1-09-T50_C', 'rap_4_BOT1-09-T50_C', 'dir_4_BOT1-09-T50_C',
       'rap_5_BOT1-09-T50_C', 'dir_5_BOT1-09-T50_C', 'rap_6_BOT1-09-T50_C',
       'dir_6_BOT1-09-T50_C', 'rap_7_BOT1-09-T50_C', 'dir_7_BOT1-09-T50_C',
       'rap_8_BOT1-09-T50_C', 'dir_8_BOT1-09-T50_C', 'rap_9_BOT1-09-T50_C',
       'dir_9_BOT1-09-T50_C', 'rap_10_BOT1-09-T50_C', 'dir_10_BOT1-09-T50_C',
       'rap_11_BOT1-09-T50_C', 'dir_11_BOT1-09-T50_C', 'rap_12_BOT1-09-T50_C',
       'dir_12_BOT1-09-T50_C', 'rap_13_BOT1-09-T50_C', 'dir_13_BOT1-09-T50_C',
       'rap_14_BOT1-09-T50_C', 'dir_14_BOT1-09-T50_C', 'rap_15_BOT1-09-T50_C',
       'dir_15_BOT1-09-T50_C', 'rap_16_BOT1-09-T50_C', 'dir_16_BOT1-09-T50_C',
       'temp_adcp_BOT1-09-T50_C', 'temp_adcp_BOT1-09-T50_NC',
       'rap_1_BOT1-09-T50_NC', 'dir_1_BOT1-09-T50_NC', 'rap_2_BOT1-09-T50_NC',
       'dir_2_BOT1-09-T50_NC', 'rap_3_BOT1-09-T50_NC', 'dir_3_BOT1-09-T50_NC',
       'rap_4_BOT1-09-T50_NC', 'dir_4_BOT1-09-T50_NC', 'rap_5_BOT1-09-T50_NC',
       'dir_5_BOT1-09-T50_NC', 'rap_6_BOT1-09-T50_NC', 'dir_6_BOT1-09-T50_NC',
       'rap_7_BOT1-09-T50_NC', 'dir_7_BOT1-09-T50_NC', 'rap_8_BOT1-09-T50_NC',
       'dir_8_BOT1-09-T50_NC', 'rap_9_BOT1-09-T50_NC', 'dir_9_BOT1-09-T50_NC'],
      dtype='str')

In [12]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [13]:
# from services.guardar_puntos_eliminados import guardar_puntos_eliminados
# nombre_de_archivo = "borrar_puntos_2"
# guardar_puntos_eliminados(app, ruta_a_carpeta, nombre_de_archivo)

In [14]:
# array_tspan = pd.date_range(start='2026-03-10 00:00:00', end='2026-06-06 23:00:00', freq='D')
# df_nc[df_nc["tspan"].isin(array_tspan)]

In [17]:
from pickle import load
nombre_archivo = "borrar_puntos_2.pkl"
ruta = os.path.join(ruta_a_carpeta, nombre_archivo)
with open(ruta, "rb") as f:
    datos = load(f)

In [18]:
datos

{'rap1': {'index': [408, 419, 720, 744, 1546],
  'tspan_num': [datetime.datetime(2026, 3, 27, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 3, 27, 12, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 4, 9, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 4, 10, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 13, 11, 0, tzinfo=datetime.timezone.utc)]},
 'rap6': {'index': [58],
  'tspan_num': [datetime.datetime(2026, 3, 12, 11, 0, tzinfo=datetime.timezone.utc)]},
 'rap7': {'index': [58],
  'tspan_num': [datetime.datetime(2026, 3, 12, 11, 0, tzinfo=datetime.timezone.utc)]}}