In [13]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *
from services.guardar_puntos_eliminados import guardar_puntos_eliminados

In [14]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [15]:
# %matplotlib tk

In [16]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [17]:
# listar_funciones_de_carga()

### 1. ADCP

In [18]:
# 1.3. p1: Crudo unido memoria-realt
nombre = "BOT1-05-T50_pkl_C"
nombre_de_archivo = "msj4_crudo_unido_realt_2026030800_2026060823.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.head(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,dir_8,rap_9,dir_9,rap_10,dir_10,rap_11,dir_11,rap_12,dir_12,temp_adcp
0,2026-03-08 00:00:00,0.08,327.5,0.10,248.0,0.14,217.9,0.07,209.7,0.06,...,199.9,0.04,200.6,0.02,226.8,0.03,196.5,46.34,225.0,25.63
1,2026-03-08 01:00:00,0.06,345.1,0.06,285.4,0.12,232.9,0.07,215.7,0.07,...,201.9,0.05,188.7,0.02,199.2,0.01,202.6,46.34,225.0,25.58

In [19]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-05-T50_NC"
nombre_de_archivo = "BOT1-05-T50-SIG500DW-NS103967-Z0.54-REALT-20260308-20260608.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,...,rap_7,dir_7,rap_8,dir_8,rap_9,dir_9,rap_10,dir_10,rap_11,dir_11
0,2026-03-08 00:00:00,25.629999,0.08,327.500000,0.10,248.000000,0.14,217.900009,0.07,209.699997,...,0.10,205.000000,0.09,199.899994,0.04,200.599991,0.02,226.800003,0.03,196.500000
1,2026-03-08 01:00:00,25.580000,0.06,345.099976,0.06,285.399994,0.12,232.899979,0.07,215.699997,...,0.12,210.099991,0.09,201.899994,0.05,188.699997,0.02,199.199997,0.01,202.599991

In [20]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-05-T50_datos_word_2026030800_2026060823.xlsx", variables="corrientes")

NAM correcto

     Variable  esperados  validados  porcentaje_validados
0          AE     2232.0     2088.0             93.548387
1   Temp adcp     2232.0     2223.0             99.596774
0       rap_1     2232.0     2205.0             98.790323
1       rap_2     2232.0     2210.0             99.014337
2       rap_3     2232.0     2211.0             99.059140
3       rap_4     2232.0     2206.0             98.835125
4       rap_5     2232.0     2205.0             98.790323
5       rap_6     2232.0     2207.0             98.879928
6       rap_7     2232.0     2210.0             99.014337
7       rap_8     2232.0     2205.0             98.790323
8       rap_9     2232.0     2194.0             98.297491
9      rap_10     2232.0     2187.0             97.983871
10     rap_11     2232.0     2189.0             98.073477

In [21]:
dict_de_boyas.keys()

dict_keys(['BOT1-05-T50_pkl_C', 'BOT1-05-T50_NC'])

In [22]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BOT1-05-T50_pkl_C', 'dir_1_BOT1-05-T50_pkl_C',
       'rap_2_BOT1-05-T50_pkl_C', 'dir_2_BOT1-05-T50_pkl_C',
       'rap_3_BOT1-05-T50_pkl_C', 'dir_3_BOT1-05-T50_pkl_C',
       'rap_4_BOT1-05-T50_pkl_C', 'dir_4_BOT1-05-T50_pkl_C',
       'rap_5_BOT1-05-T50_pkl_C', 'dir_5_BOT1-05-T50_pkl_C',
       'rap_6_BOT1-05-T50_pkl_C', 'dir_6_BOT1-05-T50_pkl_C',
       'rap_7_BOT1-05-T50_pkl_C', 'dir_7_BOT1-05-T50_pkl_C',
       'rap_8_BOT1-05-T50_pkl_C', 'dir_8_BOT1-05-T50_pkl_C',
       'rap_9_BOT1-05-T50_pkl_C', 'dir_9_BOT1-05-T50_pkl_C',
       'rap_10_BOT1-05-T50_pkl_C', 'dir_10_BOT1-05-T50_pkl_C',
       'rap_11_BOT1-05-T50_pkl_C', 'dir_11_BOT1-05-T50_pkl_C',
       'rap_12_BOT1-05-T50_pkl_C', 'dir_12_BOT1-05-T50_pkl_C',
       'temp_adcp_BOT1-05-T50_pkl_C', 'temp_adcp_BOT1-05-T50_NC',
       'rap_1_BOT1-05-T50_NC', 'dir_1_BOT1-05-T50_NC', 'rap_2_BOT1-05-T50_NC',
       'dir_2_BOT1-05-T50_NC', 'rap_3_BOT1-05-T50_NC', 'dir_3_BOT1-05-T50_NC',
       'rap_4_BOT1-05-T50_NC', 'dir_4_BOT1-05-T50_NC', 'rap_5_BOT1-05-T50_NC',
       'dir_5_BOT1-05-T50_NC', 'rap_6_BOT1-05-T50_NC', 'dir_6_BOT1-05-T50_NC',
       'rap_7_BOT1-05-T50_NC', 'dir_7_BOT1-05-T50_NC', 'rap_8_BOT1-05-T50_NC',
       'dir_8_BOT1-05-T50_NC', 'rap_9_BOT1-05-T50_NC', 'dir_9_BOT1-05-T50_NC',
       'rap_10_BOT1-05-T50_NC', 'dir_10_BOT1-05-T50_NC',
       'rap_11_BOT1-05-T50_NC', 'dir_11_BOT1-05-T50_NC'],
      dtype='str')

In [25]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [ ]:
# nombre_de_archivo = "borrar_puntos"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
# guardar_puntos_eliminados(app, ruta_a_carpeta, nombre_de_archivo)

In [23]:
from pickle import load
ruta = os.path.join(ruta_a_carpeta, "borrar_puntos.pkl")
with open(ruta, "rb") as f:
    datos = load(f)

In [24]:
datos

{'rap1': {'index': [1561],
  'tspan_num': [datetime.datetime(2026, 5, 24, 1, 0, tzinfo=datetime.timezone.utc)]},
 'rap2': {'index': [1561],
  'tspan_num': [datetime.datetime(2026, 5, 24, 1, 0, tzinfo=datetime.timezone.utc)]},
 'rap3': {'index': [961, 1009, 1249, 1297, 1561, 1707],
  'tspan_num': [datetime.datetime(2026, 4, 29, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 1, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 11, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 13, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 24, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 30, 3, 0, tzinfo=datetime.timezone.utc)]},
 'rap4': {'index': [961, 985, 1009, 1297, 1561],
  'tspan_num': [datetime.datetime(2026, 4, 29, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 4, 30, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 1, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 13, 1, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 24, 1, 0, tzinfo=datetime.timezone.utc)]}}