In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. ADCP

In [6]:
# 1.3. p1: Crudo unido .pkl
nombre = "BOT1-11-T100_pkl_C"
nombre_de_archivo = "msj4_crudo_unido_realt_2026031100_2026060623.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-11-T100\\DATOS"
df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.tail(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,rap_14,dir_14,rap_15,dir_15,rap_16,dir_16,rap_17,dir_17,temp_adcp,temperatura_mct
2110,2026-06-06 22:00:00,0.43,15.5,0.37,16.3,0.3,6.4,0.21,3.0,0.21,...,46.34,225.0,46.34,225.0,46.34,225.0,46.34,225.0,29.93,30.0
2111,2026-06-06 23:00:00,0.40,26.1,0.36,24.0,0.3,11.0,0.21,355.0,0.22,...,46.34,225.0,46.34,225.0,46.34,225.0,46.34,225.0,29.84,29.9

In [7]:
# Validado pkl
nombre = "BOT1-11-T100_pkl_V"
nombre_de_archivo = "msj4_validados_realt_2026031100_2026060623.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-11-T100\\DATOS"
df_pkl_V, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_V # Guardo el dataframe dentro
df_pkl_V.head(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,rap_9,dir_9,rap_10,dir_10,rap_11,dir_11,rap_12,dir_12,temp_adcp,temperatura_mct
0,2026-03-11 00:00:00,0.38,348.0,0.30,356.2,0.25,357.5,0.23,355.3,0.24,...,0.23,13.6,0.21,18.9,0.2,24.9,NaN,NaN,25.30,25.2
1,2026-03-11 01:00:00,NaN,NaN,0.33,358.3,0.27,1.9,0.25,1.8,0.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.24,25.2

In [8]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-11-T100_NC"
nombre_de_archivo = "BOT1-11-T100-SIG500DW-NS104481-Z0.54-REALT-20260311-20260606.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-11-T100\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,...,rap_8,dir_8,rap_9,dir_9,rap_10,dir_10,rap_11,dir_11,rap_12,dir_12
0,2026-03-11 00:00:00,25.299999,0.38,348.0,0.30,356.200012,0.25,357.499969,0.23,355.299988,...,0.26,1.300000,0.23,13.599998,0.21,18.9,0.2,24.899998,NaN,NaN
1,2026-03-11 01:00:00,25.240000,NaN,NaN,0.33,358.299988,0.27,1.900000,0.25,1.800000,...,0.25,355.299988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-11-T100\\DATOS"
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-11-T100_datos_word_2026031100_2026060623.xlsx", variables="corrientes")

NAM correcto

     Variable  esperados  validados  porcentaje_validados
0          AE     2112.0     2071.0             98.058712
1   Temp adcp     2112.0     2091.0             99.005682
0       rap_1     2112.0     2024.0             95.833333
1       rap_2     2112.0     2090.0             98.958333
2       rap_3     2112.0     2090.0             98.958333
3       rap_4     2112.0     2089.0             98.910985
4       rap_5     2112.0     2087.0             98.816288
5       rap_6     2112.0     2078.0             98.390152
6       rap_7     2112.0     2054.0             97.253788
7       rap_8     2112.0     1988.0             94.128788
8       rap_9     2112.0     1780.0             84.280303
9      rap_10     2112.0     1434.0             67.897727
10     rap_11     2112.0     1002.0             47.443182
11     rap_12     2112.0      583.0             27.604167

In [10]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BOT1-11-T100_pkl_C', 'dir_1_BOT1-11-T100_pkl_C',
       'rap_2_BOT1-11-T100_pkl_C', 'dir_2_BOT1-11-T100_pkl_C',
       'rap_3_BOT1-11-T100_pkl_C', 'dir_3_BOT1-11-T100_pkl_C',
       'rap_4_BOT1-11-T100_pkl_C', 'dir_4_BOT1-11-T100_pkl_C',
       'rap_5_BOT1-11-T100_pkl_C', 'dir_5_BOT1-11-T100_pkl_C',
       'rap_6_BOT1-11-T100_pkl_C', 'dir_6_BOT1-11-T100_pkl_C',
       'rap_7_BOT1-11-T100_pkl_C', 'dir_7_BOT1-11-T100_pkl_C',
       'rap_8_BOT1-11-T100_pkl_C', 'dir_8_BOT1-11-T100_pkl_C',
       'rap_9_BOT1-11-T100_pkl_C', 'dir_9_BOT1-11-T100_pkl_C',
       'rap_10_BOT1-11-T100_pkl_C', 'dir_10_BOT1-11-T100_pkl_C',
       'rap_11_BOT1-11-T100_pkl_C', 'dir_11_BOT1-11-T100_pkl_C',
       'rap_12_BOT1-11-T100_pkl_C', 'dir_12_BOT1-11-T100_pkl_C',
       'rap_13_BOT1-11-T100_pkl_C', 'dir_13_BOT1-11-T100_pkl_C',
       'rap_14_BOT1-11-T100_pkl_C', 'dir_14_BOT1-11-T100_pkl_C',
       'rap_15_BOT1-11-T100_pkl_C', 'dir_15_BOT1-11-T100_pkl_C',
       'rap_16_BOT1-11-T100_pkl_C', 'dir_16_BOT1-11-T100_pkl_C',
       'rap_17_BOT1-11-T100_pkl_C', 'dir_17_BOT1-11-T100_pkl_C',
       'temp_adcp_BOT1-11-T100_pkl_C', 'temperatura_mct_BOT1-11-T100_pkl_C',
       'rap_1_BOT1-11-T100_pkl_V', 'dir_1_BOT1-11-T100_pkl_V',
       'rap_2_BOT1-11-T100_pkl_V', 'dir_2_BOT1-11-T100_pkl_V',
       'rap_3_BOT1-11-T100_pkl_V', 'dir_3_BOT1-11-T100_pkl_V',
       'rap_4_BOT1-11-T100_pkl_V', 'dir_4_BOT1-11-T100_pkl_V',
       'rap_5_BOT1-11-T100_pkl_V', 'dir_5_BOT1-11-T100_pkl_V',
       'rap_6_BOT1-11-T100_pkl_V', 'dir_6_BOT1-11-T100_pkl_V',
       'rap_7_BOT1-11-T100_pkl_V', 'dir_7_BOT1-11-T100_pkl_V',
       'rap_8_BOT1-11-T100_pkl_V', 'dir_8_BOT1-11-T100_pkl_V',
       'rap_9_BOT1-11-T100_pkl_V', 'dir_9_BOT1-11-T100_pkl_V',
       'rap_10_BOT1-11-T100_pkl_V', 'dir_10_BOT1-11-T100_pkl_V',
       'rap_11_BOT1-11-T100_pkl_V', 'dir_11_BOT1-11-T100_pkl_V',
       'rap_12_BOT1-11-T100_pkl_V', 'dir_12_BOT1-11-T100_pkl_V',
       'temp_adcp_BOT1-11-T100_pkl_V', 'temperatura_mct_BOT1-11-T100_pkl_V',
       'temp_adcp_BOT1-11-T100_NC', 'rap_1_BOT1-11-T100_NC',
       'dir_1_BOT1-11-T100_NC', 'rap_2_BOT1-11-T100_NC',
       'dir_2_BOT1-11-T100_NC', 'rap_3_BOT1-11-T100_NC',
       'dir_3_BOT1-11-T100_NC', 'rap_4_BOT1-11-T100_NC',
       'dir_4_BOT1-11-T100_NC', 'rap_5_BOT1-11-T100_NC',
       'dir_5_BOT1-11-T100_NC', 'rap_6_BOT1-11-T100_NC',
       'dir_6_BOT1-11-T100_NC', 'rap_7_BOT1-11-T100_NC',
       'dir_7_BOT1-11-T100_NC', 'rap_8_BOT1-11-T100_NC',
       'dir_8_BOT1-11-T100_NC', 'rap_9_BOT1-11-T100_NC',
       'dir_9_BOT1-11-T100_NC', 'rap_10_BOT1-11-T100_NC',
       'dir_10_BOT1-11-T100_NC', 'rap_11_BOT1-11-T100_NC',
       'dir_11_BOT1-11-T100_NC', 'rap_12_BOT1-11-T100_NC',
       'dir_12_BOT1-11-T100_NC'],
      dtype='str')

In [11]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [12]:
# nombre_de_archivo = "borrar_puntos"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
# guardar_puntos_eliminados(app, ruta_a_carpeta, nombre_de_archivo)