In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. ADCP

In [6]:
# 1.3. p1: Crudo unido .pkl
nombre = "BOT1-01-T80_pkl_C"
nombre_de_archivo = "msj4_crudo_unido_realt_2026030700_2026060923.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-01-T80\\DATOS"
df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.head(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,rap_14,dir_14,rap_15,dir_15,rap_16,dir_16,rap_17,dir_17,temp_adcp,temperatura_mct
0,2026-03-07 00:00:00,0.03,3.9,0.07,59.9,0.06,117.0,0.07,164.4,0.10,...,0.18,248.3,0.18,238.8,0.14,244.7,46.34,225.0,25.22,25.0
1,2026-03-07 01:00:00,0.03,53.5,0.09,85.3,0.09,118.3,0.08,149.2,0.12,...,0.15,254.4,0.17,270.3,0.11,290.5,46.34,225.0,25.18,24.9

In [7]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-01-T80_NC"
nombre_de_archivo = "BOT1-01-T80-SIG500DW-NS104517-Z0.54-REALT-20260307-20260609.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-01-T80\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.tail(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,...,rap_11,dir_11,rap_12,dir_12,rap_13,dir_13,rap_14,dir_14,rap_15,dir_15
2278,2026-06-09 22:00:00,29.65,0.13,359.099976,0.13,31.899998,0.14,47.299995,0.13,52.499996,...,0.19,237.900009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2279,2026-06-09 23:00:00,29.58,0.11,30.900000,0.14,52.599998,0.11,65.000000,0.10,73.500000,...,0.10,208.099991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-01-T80\\DATOS"
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-01-T80_datos_word_2026030700_2026060923.xlsx", variables="corrientes")

NAM correcto

     Variable  esperados  validados  porcentaje_validados
0          AE     2280.0     2060.0             90.350877
1   Temp adcp     2280.0     2073.0             90.921053
0       rap_1     2280.0     2057.0             90.219298
1       rap_2     2280.0     2053.0             90.043860
2       rap_3     2280.0     2058.0             90.263158
3       rap_4     2280.0     2057.0             90.219298
4       rap_5     2280.0     2056.0             90.175439
5       rap_6     2280.0     2060.0             90.350877
6       rap_7     2280.0     2055.0             90.131579
7       rap_8     2280.0     2059.0             90.307018
8       rap_9     2280.0     2055.0             90.131579
9      rap_10     2280.0     2052.0             90.000000
10     rap_11     2280.0     2015.0             88.377193
11     rap_12     2280.0     1873.0             82.149123
12     rap_13     2280.0     1685.0             73.903509
13     rap_14     2280.0     1354.0             59.385965
14     rap_15     2280.0      870.0             38.157895

In [9]:
dict_de_boyas.keys()

dict_keys(['BOT1-01-T80_pkl_C', 'BOT1-01-T80_NC'])

In [10]:
# dict_de_boyas['BOT1-11-T100_NC'].head(2)

In [11]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BOT1-01-T80_pkl_C', 'dir_1_BOT1-01-T80_pkl_C',
       'rap_2_BOT1-01-T80_pkl_C', 'dir_2_BOT1-01-T80_pkl_C',
       'rap_3_BOT1-01-T80_pkl_C', 'dir_3_BOT1-01-T80_pkl_C',
       'rap_4_BOT1-01-T80_pkl_C', 'dir_4_BOT1-01-T80_pkl_C',
       'rap_5_BOT1-01-T80_pkl_C', 'dir_5_BOT1-01-T80_pkl_C',
       'rap_6_BOT1-01-T80_pkl_C', 'dir_6_BOT1-01-T80_pkl_C',
       'rap_7_BOT1-01-T80_pkl_C', 'dir_7_BOT1-01-T80_pkl_C',
       'rap_8_BOT1-01-T80_pkl_C', 'dir_8_BOT1-01-T80_pkl_C',
       'rap_9_BOT1-01-T80_pkl_C', 'dir_9_BOT1-01-T80_pkl_C',
       'rap_10_BOT1-01-T80_pkl_C', 'dir_10_BOT1-01-T80_pkl_C',
       'rap_11_BOT1-01-T80_pkl_C', 'dir_11_BOT1-01-T80_pkl_C',
       'rap_12_BOT1-01-T80_pkl_C', 'dir_12_BOT1-01-T80_pkl_C',
       'rap_13_BOT1-01-T80_pkl_C', 'dir_13_BOT1-01-T80_pkl_C',
       'rap_14_BOT1-01-T80_pkl_C', 'dir_14_BOT1-01-T80_pkl_C',
       'rap_15_BOT1-01-T80_pkl_C', 'dir_15_BOT1-01-T80_pkl_C',
       'rap_16_BOT1-01-T80_pkl_C', 'dir_16_BOT1-01-T80_pkl_C',
       'rap_17_BOT1-01-T80_pkl_C', 'dir_17_BOT1-01-T80_pkl_C',
       'temp_adcp_BOT1-01-T80_pkl_C', 'temperatura_mct_BOT1-01-T80_pkl_C',
       'temp_adcp_BOT1-01-T80_NC', 'rap_1_BOT1-01-T80_NC',
       'dir_1_BOT1-01-T80_NC', 'rap_2_BOT1-01-T80_NC', 'dir_2_BOT1-01-T80_NC',
       'rap_3_BOT1-01-T80_NC', 'dir_3_BOT1-01-T80_NC', 'rap_4_BOT1-01-T80_NC',
       'dir_4_BOT1-01-T80_NC', 'rap_5_BOT1-01-T80_NC', 'dir_5_BOT1-01-T80_NC',
       'rap_6_BOT1-01-T80_NC', 'dir_6_BOT1-01-T80_NC', 'rap_7_BOT1-01-T80_NC',
       'dir_7_BOT1-01-T80_NC', 'rap_8_BOT1-01-T80_NC', 'dir_8_BOT1-01-T80_NC',
       'rap_9_BOT1-01-T80_NC', 'dir_9_BOT1-01-T80_NC', 'rap_10_BOT1-01-T80_NC',
       'dir_10_BOT1-01-T80_NC', 'rap_11_BOT1-01-T80_NC',
       'dir_11_BOT1-01-T80_NC', 'rap_12_BOT1-01-T80_NC',
       'dir_12_BOT1-01-T80_NC', 'rap_13_BOT1-01-T80_NC',
       'dir_13_BOT1-01-T80_NC', 'rap_14_BOT1-01-T80_NC',
       'dir_14_BOT1-01-T80_NC', 'rap_15_BOT1-01-T80_NC',
       'dir_15_BOT1-01-T80_NC'],
      dtype='str')

In [12]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [ ]:
# from services.guardar_puntos_eliminados import guardar_puntos_eliminados
# nombre_de_archivo = "borrar_puntos"
# guardar_puntos_eliminados(app, ruta_a_carpeta, nombre_de_archivo)

Archivo guardado en: \\192.168.15.249\Med_2025-2026\Reportes_Edit\Reporte_1.2\2026\06. Junio\BOT1-01-T80\DATOS\borrar_puntos.pkl

{'rap1': {'index': [337],
  'tspan_num': [datetime.datetime(2026, 3, 21, 1, 0, tzinfo=datetime.timezone.utc)]},
 'rap10': {'index': [1823],
  'tspan_num': [datetime.datetime(2026, 5, 21, 23, 0, tzinfo=datetime.timezone.utc)]},
 'rap11': {'index': [1823, 2156, 2161],
  'tspan_num': [datetime.datetime(2026, 5, 21, 23, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 6, 4, 20, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 6, 5, 1, 0, tzinfo=datetime.timezone.utc)]},
 'rap12': {'index': [2156, 2161],
  'tspan_num': [datetime.datetime(2026, 6, 4, 20, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 6, 5, 1, 0, tzinfo=datetime.timezone.utc)]},
 'rap13': {'index': [1268, 2158, 2156, 1942],
  'tspan_num': [datetime.datetime(2026, 4, 28, 20, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 6, 4, 22, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 6, 4, 20, 0, tzinfo=datetime.timezone.utc),
   datetime.datetime(2026, 5, 26, 22, 0, tzinfo=datetime.timezone.utc)]}}