In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os 
import sys
import pandas as pd

sys.path.append(os.path.abspath(os.path.join('..','..')))
from services.carga_de_datos import cargar_temperaturas, leer_datos_de_pickle
from services.InteractivePlotter import InteractivePlotterTk

In [3]:
# BOT1-05-T50
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\03. Marzo\\BOT1-05-T50\\DATOS"
archivo = "msj4_crudo_unido_realt_2025111520_2026010816.pkl"
ruta_completa = os.path.join(mes, archivo)
df = leer_datos_de_pickle(ruta_completa)
df["Fecha y hora de medicion"] = pd.to_datetime(df["Fecha y hora de medicion"], format="%Y-%m-%d %H:%M:%S")

df_bot1_05_marzo = df[["Fecha y hora de medicion","Temperatura del agua (MCT P)", "Temp"]]
df_bot1_05_marzo.rename(columns={"Fecha y hora de medicion": "tspan", "Temperatura del agua (MCT P)": "temp_termistor","Temp": "temp_adcp"}, inplace=True)


mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
archivo = "msj4_crudo_unido_realt_2026030800_2026060823.pkl"
ruta_completa = os.path.join(mes, archivo)
df = leer_datos_de_pickle(ruta_completa)
df["Fecha y hora de medicion"] = pd.to_datetime(df["Fecha y hora de medicion"], format="%Y-%m-%d %H:%M:%S")
df_bot1_05_junio = df[["Fecha y hora de medicion","Temperatura del agua (MCT P)", "Temp"]]
df_bot1_05_junio.rename(columns={"Fecha y hora de medicion": "tspan", "Temperatura del agua (MCT P)": "temp_termistor","Temp": "temp_adcp"}, inplace=True)

df_bot1_05 = pd.concat([df_bot1_05_marzo, df_bot1_05_junio], ignore_index=True)
df_bot1_05.head()

                tspan  temp_termistor  temp_adcp
0 2025-11-15 20:00:00            27.4      27.78
1 2025-11-15 21:00:00            27.4      27.76
2 2025-11-15 22:00:00            27.4      27.74
3 2025-11-15 23:00:00            27.3      27.65
4 2025-11-16 00:00:00            27.2      27.47

In [4]:
# BOT1-09-T50
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\03. Marzo\\BOT1-09-T50\\DATOS"
archivo = "msj4_crudo_unido_memrealt_2025110116_2026030923.pkl"
ruta_completa = os.path.join(mes, archivo)
df = leer_datos_de_pickle(ruta_completa)
df["Fecha y hora de medicion"] = pd.to_datetime(df["Fecha y hora de medicion"], format="%Y-%m-%d %H:%M:%S")

temp_termistor_1 = df[["Fecha y hora de medicion", "Temperatura del agua (MCT P)"]]
temp_termistor_2 = df[["Fecha y hora de medicion", "Temperatura del agua (MCT)"]]
temp_termistor_2.dropna(inplace=True)
temp_termistor_1.rename(columns={"Fecha y hora de medicion": "tspan", "Temperatura del agua (MCT P)": "temp_termistor"}, inplace=True)
temp_termistor_2.rename(columns={"Fecha y hora de medicion": "tspan", "Temperatura del agua (MCT)": "temp_termistor"}, inplace=True)
df_tmp = temp_termistor_1.combine_first(temp_termistor_2)
df_temp_adcp = df[["Fecha y hora de medicion", "Temp"]]
df_temp_adcp.rename(columns={"Fecha y hora de medicion": "tspan", "Temp": "temp_adcp"}, inplace=True)
df_bot1_09_marzo = df_tmp.merge(df_temp_adcp, on="tspan", how="outer")
df_bot1_09_marzo.head()

mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
archivo = "msj4_crudo_unido_realt_2026031000_2026060623.pkl"
ruta_completa = os.path.join(mes, archivo)
df = leer_datos_de_pickle(ruta_completa)
df["Fecha y hora de medicion"] = pd.to_datetime(df["Fecha y hora de medicion"], format="%Y-%m-%d %H:%M:%S")
df_bot1_09_junio = df[["Fecha y hora de medicion","Temperatura del agua (MCT)", "Temp"]]
df_bot1_09_junio.rename(columns={"Fecha y hora de medicion": "tspan", "Temperatura del agua (MCT)": "temp_termistor", "Temp": "temp_adcp"}, inplace=True)

df_bot1_09 = pd.concat([df_bot1_09_marzo, df_bot1_09_junio], ignore_index=True)
df_bot1_09.head()

                tspan  temp_termistor  temp_adcp
0 2025-11-01 16:00:00            28.7      28.87
1 2025-11-01 17:00:00            28.8      28.94
2 2025-11-01 18:00:00            28.9      29.03
3 2025-11-01 19:00:00            29.1      29.17
4 2025-11-01 20:00:00            29.1      29.22

In [5]:
# BOT2-01-T20
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_2.2\\2026\\03. Marzo\\BOT2-01-T20\\DATOS"
archivo = "msj4_crudo_unido_realt_2025111919_2026021406.pkl"
df_bot2_01_marzo1 = cargar_temperaturas(mes, archivo)

mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_2.2\\2026\\03. Marzo\\BOT2-01-T20\\DATOS"
archivo = "msj4_crudo_unido_realt_2026022620_2026031923.pkl"
df_bot2_01_marzo2 = cargar_temperaturas(mes, archivo)

mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_2.2\\2026\\06. Junio\\BOT2-01-T20\\DATOS"
archivo = "msj4_crudo_unido_realt_2026032000_2026060823.pkl"
df_bot2_01_junio = cargar_temperaturas(mes, archivo)

df_bot2_01 = pd.concat([df_bot2_01_marzo1, df_bot2_01_marzo2, df_bot2_01_junio], ignore_index=True)
df_bot2_01.head()

                tspan  temp_termistor  temp_adcp  temp_mct
0 2025-11-19 19:00:00            28.7      28.80   28.6339
1 2025-11-19 20:00:00            28.8      28.88   28.7741
2 2025-11-19 21:00:00            28.8      28.90   28.8408
3 2025-11-19 22:00:00            28.8      28.86   28.7933
4 2025-11-19 23:00:00            28.6      28.59   28.5479

In [6]:
# BOT2-02-T20
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_2.2\\2026\\03. Marzo\\BOT2-02-T20\\DATOS"
archivo = "msj4_crudo_unido_realt_2025111821_2025122220.pkl"
df_bot2_02_marzo1 = cargar_temperaturas(mes, archivo)

archivo = "msj4_crudo_unido_realt_2025122621_2026031214.pkl"
df_bot2_02_marzo2 = cargar_temperaturas(mes, archivo)

mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_2.2\\2026\\06. Junio\\BOT2-02-T20\\DATOS"
archivo = "msj4_crudo_unido_realt_2026031215_2026060623.pkl"
df_bot2_02_junio = cargar_temperaturas(mes, archivo)

df_bot2_02 = pd.concat([df_bot2_02_marzo1, df_bot2_02_marzo2, df_bot2_02_junio], ignore_index=True)
df_bot2_02.head()

                tspan  temp_termistor  temp_adcp  temp_mct
0 2025-11-18 21:00:00            28.5      28.50   28.2349
1 2025-11-18 22:00:00            28.2      28.27   28.1931
2 2025-11-18 23:00:00             NaN        NaN       NaN
3 2025-11-19 00:00:00             NaN        NaN       NaN
4 2025-11-19 01:00:00            28.0        NaN   28.0186

In [7]:
# BMT2-01-T20
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_3.2\\2026\\03. Marzo\\BMT2-01-T20\\DATOS"
archivo = "msj4_crudo_unido_realt_2025112921_2026022816.pkl"
ruta_completa = os.path.join(mes, archivo)
df_bmt2_01 = cargar_temperaturas(mes, archivo)

df_bmt2_01.head()

                tspan  temp_adcp  temp_mct
0 2025-11-29 21:00:00        NaN       NaN
1 2025-11-29 22:00:00        NaN       NaN
2 2025-11-29 23:00:00        NaN       NaN
3 2025-11-30 00:00:00        NaN       NaN
4 2025-11-30 01:00:00        NaN       NaN

In [8]:

# BMT3-01-T2500
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\03. Marzo\\BMT3-01-T2500\\DATOS"
archivo = "msj4_crudo_unido_realt_2025110422_2026031619.pkl"
ruta_completa = os.path.join(mes, archivo)
df_bmt3_01 = cargar_temperaturas(mes, archivo)

df_bmt3_01.head()

                tspan  temp_adcp  temp_mct
0 2025-11-04 22:00:00      28.67     28.62
1 2025-11-04 23:00:00      28.66     28.60
2 2025-11-05 00:00:00      28.66     28.61
3 2025-11-05 01:00:00      28.65     28.60
4 2025-11-05 02:00:00      28.64     28.59

In [9]:

# BMT3-03-T80
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\03. Marzo\\BMT3-03-T80\\DATOS"
archivo = "msj4_crudo_unido_realt_2026022001_2026030623.pkl"
ruta_completa = os.path.join(mes, archivo)
df_bmt3_03 = cargar_temperaturas(mes, archivo)

df_bmt3_03.head()

                tspan  temp_adcp
0 2026-02-20 01:00:00      24.75
1 2026-02-20 02:00:00      24.66
2 2026-02-20 03:00:00      24.61
3 2026-02-20 04:00:00      24.59
4 2026-02-20 05:00:00      24.60

In [10]:
# BMT3-04-T45
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\03. Marzo\\BMT3-04-T45\\DATOS"
archivo = "msj4_crudo_unido_realt_2025110117_2025123105.pkl"
ruta_completa = os.path.join(mes, archivo)
df_bmt3_04_marzo1 = cargar_temperaturas(mes, archivo)

archivo = "msj4_crudo_unido_realt_2026010921_2026032415.pkl"
ruta_completa = os.path.join(mes, archivo)
df_bmt3_04_marzo2 = cargar_temperaturas(mes, archivo)

df_bmt3_04 = pd.concat([df_bmt3_04_marzo1, df_bmt3_04_marzo2], ignore_index=True)

df_bmt3_04.head()

                tspan  temp_adcp  temp_mct
0 2025-11-01 17:00:00      29.05     29.03
1 2025-11-01 18:00:00      29.11     29.10
2 2025-11-01 19:00:00      29.15     29.13
3 2025-11-01 20:00:00      29.17     29.15
4 2025-11-01 21:00:00      29.17     29.16

In [11]:
# # BMT3-10-T45
mes = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\06. Junio\\BMT3-10-T45\\DATOS"
archivo = "msj4_crudo_unido_realt_2026041603_2026060923.pkl"
ruta_completa = os.path.join(mes, archivo)
df_bmt3_10 = cargar_temperaturas(mes, archivo)

df_bmt3_10.head()

                tspan  temp_adcp  temp_mct
0 2026-04-16 03:00:00      26.49     26.43
1 2026-04-16 04:00:00      26.46     26.41
2 2026-04-16 05:00:00      26.48     26.42
3 2026-04-16 06:00:00        NaN       NaN
4 2026-04-16 07:00:00      26.44     26.39

In [15]:
df = df_bot1_05.merge(df_bot1_09, on="tspan", how="outer", suffixes=("_bot1_05", "_bot1_09"))
df = df.merge(df_bot2_01, on="tspan", how="outer", suffixes=("", "_bot2_01"))
df.rename(columns={"temp_termistor": "temp_termistor_bot2_01", "temp_adcp": "temp_adcp_bot2_01", "temp_mct": "temp_mct_bot2_01"}, inplace=True)
df = df.merge(df_bot2_02, on="tspan", how="outer", suffixes=("", "_bot2_02"))
df.rename(columns={"temp_termistor": "temp_termistor_bot2_02", "temp_adcp": "temp_adcp_bot2_02", "temp_mct": "temp_mct_bot2_02"}, inplace=True)
df = df.merge(df_bmt2_01, on="tspan", how="outer", suffixes=("", "_bmt2_01"))
df.rename(columns={"temp_adcp": "temp_adcp_bmt2_01", "temp_mct": "temp_mct_bmt2_01"}, inplace=True)
df = df.merge(df_bmt3_01, on="tspan", how="outer", suffixes=("", "_bmt3_01"))
df.rename(columns={"temp_adcp": "temp_adcp_bmt3_01", "temp_mct": "temp_mct_bmt3_01"}, inplace=True)
df = df.merge(df_bmt3_03, on="tspan", how="outer", suffixes=("", "_bmt3_03"))
df.rename(columns={"temp_adcp": "temp_adcp_bmt3_03", "temp_mct": "temp_mct_bmt3_03"}, inplace=True)
df = df.merge(df_bmt3_04, on="tspan", how="outer", suffixes=("", "_bmt3_04"))
df.rename(columns={"temp_adcp": "temp_adcp_bmt3_04", "temp_mct": "temp_mct_bmt3_04"}, inplace=True)
df = df.merge(df_bmt3_04, on="tspan", how="outer", suffixes=("", "_bmt3_10"))
df.rename(columns={"temp_adcp": "temp_adcp_bmt3_10", "temp_mct": "temp_mct_bmt3_10"}, inplace=True)

In [13]:
df.head()

,tspan,temp_termistor_bot1_05,temp_adcp_bot1_05,temp_termistor_bot1_09,temp_adcp_bot1_09,temp_termistor_bot2_01,temp_adcp_bot2_01,temp_mct_bot2_01,temp_termistor_bot2_02,temp_adcp_bot2_02,temp_mct_bot2_02,temp_adcp_bmt2_01,temp_mct_bot2_01,temp_adcp_bmt3_01,temp_mct_bot3_01,temp_adcp_bmt3_03,temp_adcp_bmt3_04,temp_mct_bot3_04,temp_adcp_bmt3_10,temp_mct_bot3_10
0,2025-11-01 16:00:00,NaN,NaN,28.7,28.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-11-01 17:00:00,NaN,NaN,28.8,28.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.05,29.03,29.05,29.03
2,2025-11-01 18:00:00,NaN,NaN,28.9,29.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.11,29.10,29.11,29.10
3,2025-11-01 19:00:00,NaN,NaN,29.1,29.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.15,29.13,29.15,29.13
4,2025-11-01 20:00:00,NaN,NaN,29.1,29.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.17,29.15,29.17,29.15

In [16]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()