In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..','..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
# p1. Crudo pkl men
nombre = "BOT2-02-T20_C"
archivos_csv = "msj3_crudo_unido_realt_2026060600_2026092823.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_2.2\\2026\\09. Septiembre\\BOT2-02-T20\\DATOS"
df_pkl_crudo_mem = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)
dict_de_boyas[nombre] = df_pkl_crudo_mem # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_mem.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-06-06 00:00:00  0.43  0.72  4.9  54.4    41.2
1 2026-06-06 01:00:00  0.43  0.71  4.9  60.6    40.7

In [ ]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BOT2-02-T20_NC1"
nombre_de_archivo = "BOT2-02-T20-TRIAXYSG3-NS09185-Z0-REALT-20260606-20260628.nc"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-06-06 00:00:00  0.43  0.72  4.9  54.4    41.2
1 2026-06-06 01:00:00  0.43  0.71  4.9  60.6    40.7

In [7]:
DirSpec[1,:,:]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(121, 129))

In [ ]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BOT2-02-T20_NC2"
nombre_de_archivo = "BOT2-02-T20-TRIAXYSG3-NS09187-Z0-REALT-20260718-20260928.nc"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-07-18 19:00:00  0.74  1.06  6.1   NaN     NaN
1 2026-07-18 20:00:00  0.82  1.25  5.6  37.1    27.8

In [9]:
DirSpec[1,:,:]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(121, 129))

In [10]:
# Otras revisiones del NC:
# comprobar_nombre_nc
# comprobar_nombre_nc(nombre_de_archivo, nc)
# comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT2-01-T20_datos_word_2026022620_2026062415.xlsx", variables="oleaje")

In [11]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BOT2-02-T20_C', 'Hmax_BOT2-02-T20_C', 'Tp_BOT2-02-T20_C',
       'dir_BOT2-02-T20_C', 'vardir_BOT2-02-T20_C', 'Hs_BOT2-02-T20_NC1',
       'Hmax_BOT2-02-T20_NC1', 'Tp_BOT2-02-T20_NC1', 'dir_BOT2-02-T20_NC1',
       'vardir_BOT2-02-T20_NC1', 'Hs_BOT2-02-T20_NC2', 'Hmax_BOT2-02-T20_NC2',
       'Tp_BOT2-02-T20_NC2', 'dir_BOT2-02-T20_NC2', 'vardir_BOT2-02-T20_NC2'],
      dtype='str')

In [12]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [13]:
# nombre_de_archivo = "borrar_puntos"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
# guardar_puntos_eliminados(app, ruta_a_carpeta, nombre_de_archivo)