In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..','..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *
from services.carga_meses_de_telemetria import cargar_telemetria_meteo_validados

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. Meteo

In [6]:
# 1.3. p1: Crudo unido .pkl
nombre = "BMT3-10-T45_C"
nombre_de_archivo = "msj1_crudo_unido_realt_2026061000_2026082023.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\08. Agosto\\BMT3-10-T45\\DATOS"
df_pkl_C = cargar_pickle_meteo(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.head(2)

,tspan,Pa,Ta,HR,Punto de Rocio,Rap2,Dir2,u (mecanico),v (mecanico),R5s2,...,u (sonico),v (sonico),R5s1,R1s1,Temperatura (sonico),Presion (sonico),Humedad relativa (sonico),Lluvia acumulada,Duracion de la lluvia,Intensidad de la lluvia
0,2026-06-10 00:00:00,1008.42,29.5,85.9,26.9,8.2,28.0,3.849667,7.240170,9.7,...,3.402967,7.789083,10.2,10.8,29.3,1009.7,83.9,52.2,8670.0,0.0
1,2026-06-10 01:00:00,1007.92,29.3,88.4,27.2,9.1,32.0,4.822265,7.717238,10.9,...,4.441977,8.284252,11.6,12.3,29.1,1009.2,86.2,52.2,8670.0,0.0

In [7]:
# 1.4. Cargar NETCDF 
nombre = "BMT3-10-T45_NC"
nombre_de_archivo = "BMT3-10-T45-METEO-NS506530-A4-REALT-20260610-20260820.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\08. Agosto\\BMT3-10-T45\\DATOS"
df_nc, nc = cargar_nc_meteo(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.tail(2)

,tspan,Pa,Ta,HR,Rap1,Dir1,R5s1,R1s1,R5s2,R1s2,Rap2,Dir2
1726,2026-08-20 22:00:00,1012.18,29.2,82.0,4.9,19.5,5.8,6.4,5.5,5.88,4.7,26.0
1727,2026-08-20 23:00:00,1012.03,29.3,83.8,6.6,18.7,8.0,8.8,7.6,7.99,6.3,23.0

In [8]:
df_nc.head(2)

,tspan,Pa,Ta,HR,Rap1,Dir1,R5s1,R1s1,R5s2,R1s2,Rap2,Dir2
0,2026-06-10 00:00:00,1008.42,29.5,85.9,8.5,23.6,10.2,10.8,9.7,10.24,8.2,28.0
1,2026-06-10 01:00:00,1007.92,29.3,88.4,9.4,28.2,11.6,12.3,10.9,11.59,9.1,32.0

In [9]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\08. Agosto\\BMT3-10-T45\\DATOS"
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "porcentajes_2026061000_2026082023_msj1_telemetria.xlsx", variables="meteo")

NAM correcto

   Variable  esperados  validados  porcentaje_validados
0        Pa       1728       1721             99.594907
1        Ta       1728       1721             99.594907
2        HR       1728       1721             99.594907
3      Rap1       1728       1721             99.594907
4      Dir1       1728       1721             99.594907
5      R1s1       1728       1721             99.594907
6      R5s1       1728       1721             99.594907
7      Rap2       1728       1721             99.594907
8      Dir2       1728       1721             99.594907
9      R1s2       1728       1721             99.594907
10     R5s2       1728       1721             99.594907

In [10]:
# 1.4. Cargar BOT1-10-T40
nombre_de_boya = "BMT2-01-T20"
dict_de_boyas[nombre_de_boya] = cargar_telemetria_meteo_validados(nombre_de_boya, [2026, 2026], [6, 7])

In [11]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Pa_BMT3-10-T45_C', 'Ta_BMT3-10-T45_C', 'HR_BMT3-10-T45_C',
       'Punto de Rocio_BMT3-10-T45_C', 'Rap2_BMT3-10-T45_C',
       'Dir2_BMT3-10-T45_C', 'u (mecanico)_BMT3-10-T45_C',
       'v (mecanico)_BMT3-10-T45_C', 'R5s2_BMT3-10-T45_C',
       'R1s2_BMT3-10-T45_C', 'Rap1_BMT3-10-T45_C', 'Dir1_BMT3-10-T45_C',
       'u (sonico)_BMT3-10-T45_C', 'v (sonico)_BMT3-10-T45_C',
       'R5s1_BMT3-10-T45_C', 'R1s1_BMT3-10-T45_C',
       'Temperatura (sonico)_BMT3-10-T45_C', 'Presion (sonico)_BMT3-10-T45_C',
       'Humedad relativa (sonico)_BMT3-10-T45_C',
       'Lluvia acumulada_BMT3-10-T45_C', 'Duracion de la lluvia_BMT3-10-T45_C',
       'Intensidad de la lluvia_BMT3-10-T45_C', 'Pa_BMT3-10-T45_NC',
       'Ta_BMT3-10-T45_NC', 'HR_BMT3-10-T45_NC', 'Rap1_BMT3-10-T45_NC',
       'Dir1_BMT3-10-T45_NC', 'R5s1_BMT3-10-T45_NC', 'R1s1_BMT3-10-T45_NC',
       'R5s2_BMT3-10-T45_NC', 'R1s2_BMT3-10-T45_NC', 'Rap2_BMT3-10-T45_NC',
       'Dir2_BMT3-10-T45_NC', 'Pa_BMT2-01-T20', 'Ta_BMT2-01-T20',
       'HR_BMT2-01-T20', 'Punto de Rocio_BMT2-01-T20', 'Rap2_BMT2-01-T20',
       'Dir2_BMT2-01-T20', 'u (mecanico)_BMT2-01-T20',
       'v (mecanico)_BMT2-01-T20', 'R5s2_BMT2-01-T20', 'R1s2_BMT2-01-T20',
       'Rap1_BMT2-01-T20', 'Dir1_BMT2-01-T20', 'u (sonico)_BMT2-01-T20',
       'v (sonico)_BMT2-01-T20', 'R5s1_BMT2-01-T20', 'R1s1_BMT2-01-T20',
       'Temperatura (sonico)_BMT2-01-T20', 'Presion (sonico)_BMT2-01-T20',
       'Humedad relativa (sonico)_BMT2-01-T20', 'Lluvia acumulada_BMT2-01-T20',
       'Duracion de la lluvia_BMT2-01-T20',
       'Intensidad de la lluvia_BMT2-01-T20'],
      dtype='str')

In [12]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [13]:
# from services.guardar_puntos_eliminados import guardar_puntos_eliminados
# nombre_de_archivo = "borrar_puntos"
# guardar_puntos_eliminados(app, ruta_a_carpeta, nombre_de_archivo)