In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..','..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
p1 = pd.date_range('2026-03-01 00:00', '2026-06-27 01:00', freq='h') 
total = p1
print(f"p1 = {len(p1)}, total = {len(total)}")

p1 = 2834, total = 2834

In [6]:
# p1: Crudo unido pkl
nombre = "BOT1-10-T40_pkl"
nombre_de_archivo = "msj3_crudo_unido_realt_2026030100_2026062701.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-10-T40\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-03-01 00:00:00  0.49  0.83  3.9  10.6    33.6
1 2026-03-01 01:00:00  0.54  0.91  3.6   6.2    31.0

In [7]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BOT1-10-T40_NC"
nombre_de_archivo = "BOT1-10-T40-TRIAXYSG3-NS09162-Z0-REALT-20260301-20260627.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-10-T40\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-03-01 00:00:00  0.49  0.83  3.9  10.6    33.6
1 2026-03-01 01:00:00  0.54  0.91  3.6   6.2    31.0

In [8]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-10-T40_datos_word_2026030100_2026062701.xlsx", variables="oleaje")

NAM correcto

  Variable  esperados  validados  porcentaje_validados
0       Hs       2834     2831.0             99.894143
1       Hm       2834     2831.0             99.894143
2       Tp       2834     2831.0             99.894143
3      dir       2834     2831.0             99.894143
4   vardir       2834     2831.0             99.894143
5  dirspec       2834     2704.0             95.412844

In [9]:
# 1.5. p2: Cargar NETCDF de corrientes 
nombre = "BOT1-07-T80_NC"
nombre_de_archivo = "BOT1-07-T80-TRIAXYSG3-NS09171-Z0-MEMREALT-20260213-20260713.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-07-T80\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-02-13 21:00:00  0.60  1.00  5.4  57.0    32.0
1 2026-02-13 22:00:00  0.49  0.78  5.0  52.0    32.0

In [10]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BOT1-10-T40_pkl', 'Hmax_BOT1-10-T40_pkl',
       'Tp_BOT1-10-T40_pkl', 'dir_BOT1-10-T40_pkl', 'vardir_BOT1-10-T40_pkl',
       'Hs_BOT1-10-T40_NC', 'Hmax_BOT1-10-T40_NC', 'Tp_BOT1-10-T40_NC',
       'dir_BOT1-10-T40_NC', 'vardir_BOT1-10-T40_NC', 'Hs_BOT1-07-T80_NC',
       'Hmax_BOT1-07-T80_NC', 'Tp_BOT1-07-T80_NC', 'dir_BOT1-07-T80_NC',
       'vardir_BOT1-07-T80_NC'],
      dtype='str')

In [11]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [12]:
# idxs = app.deletion_log["vardir_BOT1-04-T80_pkl_realt_V"]["idxs"]
# tspan_num = mdates.num2date(app.data.loc[idxs,"tspan"])
# tspan_pd = pd.to_datetime(tspan_num)
# df_out = pd.DataFrame({"tspan": tspan_pd})
# df_out.to_csv("tspan_eliminados.csv", index=False)