In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. ADCP

In [6]:
# # P1. DAT
# nombre = "BOT1-09-T50_dat"
# nombre_de_archivo = "BOT1-09-T50-MENSAJE4-SIG500DW-NS104499-Z0.54-REALT-20251101-20251207-RAW.dat"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-09-T50\\DATOS"
# fecha_inicio = "2025-11-01 16:00:00"
# fecha_fin = "2025-12-07 14:59:59"
# indices = Crear_indices_para_crudos_dat_o_txt("realt").get_indices()
# df_dat = cargar_telemetria_adcp_dat(ruta_a_carpeta, nombre_de_archivo, indices,fecha_inicio, fecha_fin)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [7]:
# # P2. DAT
# nombre = "BOT1-09-T50_dat"
# nombre_de_archivo = "BOT1-09-T50-MENSAJE4-SIG500DW-NS104499-Z0.54-REALT-20260320-20260606-RAW.dat"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
# fecha_inicio = "2025-11-01 15:00:00"
# fecha_fin = "2026-03-24 23:59:59"
# indices = Crear_indices_para_crudos_dat_o_txt("realt").get_indices()
# df_dat = cargar_telemetria_adcp_dat(ruta_a_carpeta, nombre_de_archivo, indices,fecha_inicio, fecha_fin)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [8]:
# 1.3. p1: Crudo
nombre = "BOT1-09-T50_C1_crudo"
nombre_de_archivo = "msj4_crudo_unido_realt_2026032000_2026060623.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.head(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,rap_13,dir_13,rap_14,dir_14,rap_15,dir_15,rap_16,dir_16,temp_adcp,temperatura_mct
0,2026-03-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-20 01:00:00,0.25,336.1,0.31,344.9,0.31,351.6,0.29,353.1,0.28,...,46.34,225.0,46.34,225.0,46.34,225.0,46.34,225.0,24.51,24.4

In [9]:
# p2: Crudo validados
nombre = "BOT1-09-T50_C2_validados"
nombre_de_archivo = "msj4_validados_realt_2026032000_2026060623.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
df_pkl_V, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_V # Guardo el dataframe dentro
df_pkl_V.head(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,rap_6,dir_6,rap_7,dir_7,rap_8,dir_8,rap_9,dir_9,temp_adcp,temperatura_mct
0,2026-03-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-20 01:00:00,0.25,336.1,0.31,344.9,0.31,351.6,0.29,353.1,0.28,...,0.28,346.2,0.27,344.8,0.24,344.7,0.1,348.0,24.51,24.4

In [10]:
# # 1.3. p1 y p2: Validado unido memoria-realt
# nombre = "BOT1-09-T50_pkl_V"
# nombre_de_archivo = "msj4_validados_memrealt_2025110116_2026030923.pkl"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-09-T50\\DATOS"
# df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
# dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
# df_pkl_C.head(2)

In [19]:
# 1.4. p1. NC 1 - REALT
nombre = "BOT1-09-T50_NC1"
nombre_de_archivo = "BOT1-09-T50-SIG500DW-NS104499-Z0.54-REALT-20260320-20260606.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.tail(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,dir_5,rap_6,dir_6,rap_7,dir_7,rap_8,dir_8,rap_9,dir_9
1894,2026-06-06 22:00:00,29.74,0.11,145.599991,0.12,91.399994,0.04,120.999992,0.05,213.699997,0.1,217.300003,0.1,208.099991,0.1,214.500000,0.08,229.0,0.03,236.300003
1895,2026-06-06 23:00:00,29.51,0.10,180.600006,0.12,114.199989,0.04,135.000000,0.05,225.799988,0.1,220.699997,0.1,214.699997,0.1,224.200012,0.08,240.0,0.04,263.500000

In [11]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-09-T50\\DATOS"
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-09-T50_datos_word_2026032000_2026060623.xlsx", variables="corrientes")

NAM correcto

    Variable  esperados  validados  porcentaje_validados
0         AE     1896.0     1850.0             97.573840
1  Temp adcp     1896.0     1784.0             94.092827
0      rap_1     1896.0     1777.0             93.723629
1      rap_2     1896.0     1781.0             93.934599
2      rap_3     1896.0     1778.0             93.776371
3      rap_4     1896.0     1782.0             93.987342
4      rap_5     1896.0     1780.0             93.881857
5      rap_6     1896.0     1780.0             93.881857
6      rap_7     1896.0     1778.0             93.776371
7      rap_8     1896.0     1775.0             93.618143
8      rap_9     1896.0     1771.0             93.407173

In [12]:
# # 1.4. p2. NC 2 - REALT
# nombre = "BOT1-09-T50_NC2"
# nombre_de_archivo = "BOT1-09-T50-SIG500DW-NS104499-Z0.54-REALT-20251207-20260309.nc"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-09-T50\\DATOS"
# df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
# dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
# df_nc.head(2)

In [13]:
# Otras revisiones del NC:
# # comprobar_nombre_nc
# comprobar_nombre_nc(nombre_de_archivo, nc)
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-09-T50\\DATOS"
# comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-09-T50_datos_word_2025120717_2026030923.xlsx", variables="corrientes")

In [14]:
dict_de_boyas.keys()

dict_keys(['BOT1-09-T50_C1_crudo', 'BOT1-09-T50_C2_validados', 'BOT1-09-T50_NC1'])

In [15]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BOT1-09-T50_C1_crudo', 'dir_1_BOT1-09-T50_C1_crudo',
       'rap_2_BOT1-09-T50_C1_crudo', 'dir_2_BOT1-09-T50_C1_crudo',
       'rap_3_BOT1-09-T50_C1_crudo', 'dir_3_BOT1-09-T50_C1_crudo',
       'rap_4_BOT1-09-T50_C1_crudo', 'dir_4_BOT1-09-T50_C1_crudo',
       'rap_5_BOT1-09-T50_C1_crudo', 'dir_5_BOT1-09-T50_C1_crudo',
       'rap_6_BOT1-09-T50_C1_crudo', 'dir_6_BOT1-09-T50_C1_crudo',
       'rap_7_BOT1-09-T50_C1_crudo', 'dir_7_BOT1-09-T50_C1_crudo',
       'rap_8_BOT1-09-T50_C1_crudo', 'dir_8_BOT1-09-T50_C1_crudo',
       'rap_9_BOT1-09-T50_C1_crudo', 'dir_9_BOT1-09-T50_C1_crudo',
       'rap_10_BOT1-09-T50_C1_crudo', 'dir_10_BOT1-09-T50_C1_crudo',
       'rap_11_BOT1-09-T50_C1_crudo', 'dir_11_BOT1-09-T50_C1_crudo',
       'rap_12_BOT1-09-T50_C1_crudo', 'dir_12_BOT1-09-T50_C1_crudo',
       'rap_13_BOT1-09-T50_C1_crudo', 'dir_13_BOT1-09-T50_C1_crudo',
       'rap_14_BOT1-09-T50_C1_crudo', 'dir_14_BOT1-09-T50_C1_crudo',
       'rap_15_BOT1-09-T50_C1_crudo', 'dir_15_BOT1-09-T50_C1_crudo',
       'rap_16_BOT1-09-T50_C1_crudo', 'dir_16_BOT1-09-T50_C1_crudo',
       'temp_adcp_BOT1-09-T50_C1_crudo',
       'temperatura_mct_BOT1-09-T50_C1_crudo',
       'rap_1_BOT1-09-T50_C2_validados', 'dir_1_BOT1-09-T50_C2_validados',
       'rap_2_BOT1-09-T50_C2_validados', 'dir_2_BOT1-09-T50_C2_validados',
       'rap_3_BOT1-09-T50_C2_validados', 'dir_3_BOT1-09-T50_C2_validados',
       'rap_4_BOT1-09-T50_C2_validados', 'dir_4_BOT1-09-T50_C2_validados',
       'rap_5_BOT1-09-T50_C2_validados', 'dir_5_BOT1-09-T50_C2_validados',
       'rap_6_BOT1-09-T50_C2_validados', 'dir_6_BOT1-09-T50_C2_validados',
       'rap_7_BOT1-09-T50_C2_validados', 'dir_7_BOT1-09-T50_C2_validados',
       'rap_8_BOT1-09-T50_C2_validados', 'dir_8_BOT1-09-T50_C2_validados',
       'rap_9_BOT1-09-T50_C2_validados', 'dir_9_BOT1-09-T50_C2_validados',
       'temp_adcp_BOT1-09-T50_C2_validados',
       'temperatura_mct_BOT1-09-T50_C2_validados', 'temp_adcp_BOT1-09-T50_NC1',
       'rap_1_BOT1-09-T50_NC1', 'dir_1_BOT1-09-T50_NC1',
       'rap_2_BOT1-09-T50_NC1', 'dir_2_BOT1-09-T50_NC1',
       'rap_3_BOT1-09-T50_NC1', 'dir_3_BOT1-09-T50_NC1',
       'rap_4_BOT1-09-T50_NC1', 'dir_4_BOT1-09-T50_NC1',
       'rap_5_BOT1-09-T50_NC1', 'dir_5_BOT1-09-T50_NC1',
       'rap_6_BOT1-09-T50_NC1', 'dir_6_BOT1-09-T50_NC1',
       'rap_7_BOT1-09-T50_NC1', 'dir_7_BOT1-09-T50_NC1',
       'rap_8_BOT1-09-T50_NC1', 'dir_8_BOT1-09-T50_NC1',
       'rap_9_BOT1-09-T50_NC1', 'dir_9_BOT1-09-T50_NC1'],
      dtype='str')

In [16]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [18]:
dict_out = {}
for key in app.deletion_log.keys():
    idxs = app.deletion_log[key]["idxs"]
    tspan_num = mdates.num2date(app.data.loc[idxs,"tspan"])
    tspan_pd = pd.to_datetime(tspan_num)

    new_key_name = "".join(key.split("_")[0:1])
    dict_out[new_key_name] = tspan_pd

df_out = pd.DataFrame({"tspan": tspan_pd,
                        "columna": [key]*len(tspan_pd)
                        })

df_out.to_csv("tspan_eliminados.csv", index=False)