In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. Meteo

In [6]:
# # 1.1. Cargar telemetría .dat
# nombre = "BMT2-01-T20_dat"
# nombre_de_archivo = "BMT2-01-T20-MENSAJE1-MET-NS506930-A3-REALT-20251129-20260228-RAW.dat"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT2-01-T20\\DATOS"
# indices = Crear_indices_para_crudos_dat_o_txt("realt").get_indices()
# df_dat = cargar_telemetria_meteo_dat(ruta_a_carpeta, nombre_de_archivo, indices)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [7]:
# 1.3. p1: Crudo unido .pkl
nombre = "BMT2-01-T20_pkl_C"
nombre_de_archivo = "msj1_crudo_unido_realt_2025112921_2026022816.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT2-01-T20\\DATOS"
df_pkl_C = cargar_pickle_meteo(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.head(2)

,tspan,Pa,Ta,HR,Punto de Rocio,Rap2,Dir2,u (mecanico),v (mecanico),R5s2,...,u (sonico),v (sonico),R5s1,R1s1,Temperatura (sonico),Presion (sonico),Humedad relativa (sonico),Lluvia acumulada,Duracion de la lluvia,Intensidad de la lluvia
0,2025-11-29 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-11-29 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# # Validado pkl
# nombre = "BMT2-01-T20_pkl_V"
# nombre_de_archivo = "msj1_validados_realt_2025112921_2026022816.pkl"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT2-01-T20\\DATOS"
# df_pkl_V = cargar_pickle_meteo(ruta_a_carpeta, nombre_de_archivo)
# dict_de_boyas[nombre] = df_pkl_V # Guardo el dataframe dentro
# # df_pkl_V.head()
# print(df_pkl_V[70:120])

In [9]:
# 1.4. Cargar NETCDF 
nombre = "BMT2-01-T20_NC"
nombre_de_archivo = "BMT2-01-T20-METEO-NS506930-A4-REALT-20251129-20260228.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT2-01-T20\\DATOS"
df_nc, nc = cargar_nc_meteo(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(5)

,tspan,Pa,Ta,HR,Rap1,Dir1,R5s1,R1s1,R5s2,R1s2,Rap2,Dir2
0,2025-11-29 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-11-29 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-11-29 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-11-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-11-30 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT2-01-T20\\DATOS"
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BMT2-01-T20_datos_word_2025112921_2026022816.xlsx", variables="meteo")

In [ ]:
# Validado pkl
nombre = "BMT3-03-T80"
nombre_de_archivo = "msj1_validados_realt_2025110620_2026030623.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT3-03-T80\\DATOS"
df_pkl_V = cargar_pickle_meteo(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_V # Guardo el dataframe dentro
# df_pkl_V.head()
print(df_pkl_V[70:120])

In [ ]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

In [ ]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)