In [1]:
import os
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
# Archivo .dat de oleaje
# nombre = "BOT1-10-T40_DAT"
# nombre_de_archivo = "BOT1-10-T40-MENSAJE4-SIG500DW-NS103996-Z0.54-REALT-20251108-20260228-RAW.dat"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-10-T40\\DATOS"
# indices = Crear_indices_para_crudos_dat_o_txt("realt").get_indices()
# df_dat = cargar_telemetria_oleaje_dat(ruta_a_carpeta, nombre_de_archivo, indices)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [6]:
# 1.1. p1: Cargar crudo mem unido (binario mem + telemetría mem + binario realt + telemetría realt)
nombre = "BOT1-07-T80_pkl_mem_C1"
archivos_csv = "msj3_crudo_unido_mem_2025110117_2026021320.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-07-T80\\DATOS"
df_pkl_crudo_mem = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)
dict_de_boyas[nombre] = df_pkl_crudo_mem # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_mem.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 17:00:00  0.73  1.12  6.9  357.0    22.0
1 2025-11-01 18:00:00  0.60  1.06  6.5   35.0    25.0

In [7]:
# 1.2. p1: Cargar telemetría cruda_unida .pkl (Binario + telemetría)
nombre = "BOT1-07-T80_pkl_realt_C1"
nombre_de_archivo = "msj3_crudo_unido_realt_2025110117_2026021320.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-07-T80\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 17:00:00  0.73  1.12  6.9  357.1    21.5
1 2025-11-01 18:00:00  0.60  1.06  6.5   35.4    25.4

In [8]:
# 1.3. p2: Crudos unidos realt
nombre = "BOT1-07-T80_pkl_realt_C2"
nombre_de_archivo = "msj3_crudo_unido_realt_2026021321_2026030223.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-07-T80\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-02-13 21:00:00  0.60  1.00  5.4  57.4    32.3
1 2026-02-13 22:00:00  0.49  0.78  5.0  52.3    32.2

In [9]:
# 1.4. Cargar datos validados memrealt .pkl (todo el periodo)
nombre = "BOT1-07-T80_pkl_realt_V"
nombre_de_archivo = "msj3_validados_memrealt_2025110117_2026030223.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-07-T80\\DATOS"
df_pkl_validados = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_validados # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_validados.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 17:00:00  0.73  1.12  6.9  357.0    22.0
1 2025-11-01 18:00:00  0.60  1.06  6.5   35.0    25.0

In [10]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BOT1-07-T40_NC1"
nombre_de_archivo = "BOT1-07-T80-TRIAXYSG3-NS09113-Z0-MEM-20251101-20260213.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-07-T80\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 17:00:00  0.73  1.12  6.9  357.0    22.0
1 2025-11-01 18:00:00  0.60  1.06  6.5   35.0    25.0

In [11]:
# 1.6. p2: Cargar NETCDF de corrientes 
nombre = "BOT1-07-T40_NC2"
nombre_de_archivo = "BOT1-07-T80-TRIAXYSG3-NS09171-Z0-REALT-20260213-20260302.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-07-T80\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-02-13 21:00:00  0.60  1.00  5.4  57.4    32.3
1 2026-02-13 22:00:00  0.49  0.78  5.0  52.3    32.2

In [12]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
# comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-10-T40_datos_word_2025110818_2026022823.xlsx", variables="oleaje")

NAM correcto

In [13]:
# 1.4. Cargar NETCDF de corrientes otra boya para referencia
nombre = "BOT1-10-T40_NC"
nombre_de_archivo = "BOT1-10-T40-TRIAXYSG3-NS09162-Z0-REALT-20251108-20260228.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-10-T40\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-08 18:00:00  0.50  0.84  3.4  78.5    35.8
1 2025-11-08 19:00:00  0.45  0.75  3.4  81.0    33.7

In [14]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BOT1-07-T80_pkl_mem_C1', 'Hmax_BOT1-07-T80_pkl_mem_C1',
       'Tp_BOT1-07-T80_pkl_mem_C1', 'dir_BOT1-07-T80_pkl_mem_C1',
       'vardir_BOT1-07-T80_pkl_mem_C1', 'Hs_BOT1-07-T80_pkl_realt_C1',
       'Hmax_BOT1-07-T80_pkl_realt_C1', 'Tp_BOT1-07-T80_pkl_realt_C1',
       'dir_BOT1-07-T80_pkl_realt_C1', 'vardir_BOT1-07-T80_pkl_realt_C1',
       'Hs_BOT1-07-T80_pkl_realt_C2', 'Hmax_BOT1-07-T80_pkl_realt_C2',
       'Tp_BOT1-07-T80_pkl_realt_C2', 'dir_BOT1-07-T80_pkl_realt_C2',
       'vardir_BOT1-07-T80_pkl_realt_C2', 'Hs_BOT1-07-T80_pkl_realt_V',
       'Hmax_BOT1-07-T80_pkl_realt_V', 'Tp_BOT1-07-T80_pkl_realt_V',
       'dir_BOT1-07-T80_pkl_realt_V', 'vardir_BOT1-07-T80_pkl_realt_V',
       'Hs_BOT1-07-T40_NC1', 'Hmax_BOT1-07-T40_NC1', 'Tp_BOT1-07-T40_NC1',
       'dir_BOT1-07-T40_NC1', 'vardir_BOT1-07-T40_NC1', 'Hs_BOT1-07-T40_NC2',
       'Hmax_BOT1-07-T40_NC2', 'Tp_BOT1-07-T40_NC2', 'dir_BOT1-07-T40_NC2',
       'vardir_BOT1-07-T40_NC2', 'Hs_BOT1-10-T40_NC', 'Hmax_BOT1-10-T40_NC',
       'Tp_BOT1-10-T40_NC', 'dir_BOT1-10-T40_NC', 'vardir_BOT1-10-T40_NC'],
      dtype='str')

In [15]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)