In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
# # Archivo .dat de oleaje
# nombre = "BOT1-11-T100_DAT"
# nombre_de_archivo = "BOT1-11-T100-MENSAJE3-TRIAXYSG3-NS09276-Z0-REALT-20251119-20260310-RAW.dat"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-11-T100\\DATOS"
# indices = Crear_indices_para_crudos_dat_o_txt("realt").get_indices()
# df_dat = cargar_telemetria_oleaje_dat(ruta_a_carpeta, nombre_de_archivo, indices)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [6]:
# 1.1. Cargar crudo pkl (binario + telemetría)
nombre = "BOT1-04-T80_pkl_realt_C"
archivos_csv = "msj3_crudo_unido_realt_2025110115_2026032423.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-04-T80\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 15:00:00  0.66  1.02  6.7  344.0    35.5
1 2025-11-01 16:00:00  0.69  1.12  6.3  352.1    33.3

In [7]:
# 1.4. Cargar datos validados (binarios + telemetría)
nombre = "BOT1-04-T80_pkl_realt_V"
nombre_de_archivo = "msj3_validados_realt_2025110115_2026032423.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-04-T80\\DATOS"
df_pkl_validados = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_validados # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_validados.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 15:00:00  0.66  1.02  6.7  344.0    35.5
1 2025-11-01 16:00:00  0.69  1.12  6.3  352.1    33.3

In [8]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BOT1-04-T80_NC"
nombre_de_archivo = "BOT1-04-T80-TRIAXYSG3-NS09294-Z0-REALT-20251101-20260324.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-04-T80\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 15:00:00  0.66  1.02  6.7  344.0    35.5
1 2025-11-01 16:00:00  0.69  1.12  6.3  352.1    33.3

In [9]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-11-T100_datos_word_2025111913_2026031023.xlsx", variables="oleaje")

NAM correcto

  Variable  esperados  validados  porcentaje_validados
0       Hs       3441     3427.0             99.593142
1       Hm       3441     3427.0             99.593142
2       Tp       3441     3427.0             99.593142
3      dir       3441     3343.0             97.151991
4   vardir       3441     3343.0             97.151991
5  dirspec       3441     2666.0             77.477477

In [10]:
nombre = "BOT1-03-T50_NC1"
nombre_de_archivo = "BOT1-03-T50-TRIAXYSG3-NS09293-Z0-REALT-20251117-20251230.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-03-T50\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-17 17:00:00  0.47  0.80  3.3  88.5    31.6
1 2025-11-17 18:00:00  0.39  0.74  3.2  72.0    35.5

In [11]:
nombre = "BOT1-03-T50_NC2"
nombre_de_archivo = "BOT1-03-T50-TRIAXYSG3-NS09295-Z0-REALT-20260117-20260303.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-03-T50\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-01-17 21:00:00  0.85  1.31  4.8  59.0    33.8
1 2026-01-17 22:00:00  0.80  1.41  4.8  58.6    31.2

In [12]:
nombre = "BMT3-04-T45_pkl_realt_C1"
archivos_pkl = "msj3_crudo_unido_realt_2025110117_2025123005.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT3-04-T45\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivos_pkl)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-01 17:00:00  0.63  1.03  7.1  30.9    37.9
1 2025-11-01 18:00:00  0.59  1.02  7.1  33.8    39.7

In [13]:
nombre = "BMT3-04-T45_pkl_realt_C2"
archivos_pkl = "msj3_crudo_unido_realt_2026010921_2026032423.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BMT3-04-T45\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivos_pkl)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-01-09 21:00:00  0.64  0.98  5.9  62.3    25.4
1 2026-01-09 22:00:00  0.51  0.88  5.4  60.0    28.4

In [14]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BOT1-04-T80_pkl_realt_C', 'Hmax_BOT1-04-T80_pkl_realt_C',
       'Tp_BOT1-04-T80_pkl_realt_C', 'dir_BOT1-04-T80_pkl_realt_C',
       'vardir_BOT1-04-T80_pkl_realt_C', 'Hs_BOT1-04-T80_pkl_realt_V',
       'Hmax_BOT1-04-T80_pkl_realt_V', 'Tp_BOT1-04-T80_pkl_realt_V',
       'dir_BOT1-04-T80_pkl_realt_V', 'vardir_BOT1-04-T80_pkl_realt_V',
       'Hs_BOT1-04-T80_NC', 'Hmax_BOT1-04-T80_NC', 'Tp_BOT1-04-T80_NC',
       'dir_BOT1-04-T80_NC', 'vardir_BOT1-04-T80_NC', 'Hs_BOT1-03-T50_NC1',
       'Hmax_BOT1-03-T50_NC1', 'Tp_BOT1-03-T50_NC1', 'dir_BOT1-03-T50_NC1',
       'vardir_BOT1-03-T50_NC1', 'Hs_BOT1-03-T50_NC2', 'Hmax_BOT1-03-T50_NC2',
       'Tp_BOT1-03-T50_NC2', 'dir_BOT1-03-T50_NC2', 'vardir_BOT1-03-T50_NC2',
       'Hs_BMT3-04-T45_pkl_realt_C1', 'Hmax_BMT3-04-T45_pkl_realt_C1',
       'Tp_BMT3-04-T45_pkl_realt_C1', 'dir_BMT3-04-T45_pkl_realt_C1',
       'vardir_BMT3-04-T45_pkl_realt_C1', 'Hs_BMT3-04-T45_pkl_realt_C2',
       'Hmax_BMT3-04-T45_pkl_realt_C2', 'Tp_BMT3-04-T45_pkl_realt_C2',
       'dir_BMT3-04-T45_pkl_realt_C2', 'vardir_BMT3-04-T45_pkl_realt_C2'],
      dtype='str')

In [15]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [16]:
idxs = app.deletion_log["vardir_BOT1-04-T80_pkl_realt_V"]["idxs"]
tspan_num = mdates.num2date(app.data.loc[idxs,"tspan"])
tspan_pd = pd.to_datetime(tspan_num)
df_out = pd.DataFrame({"tspan": tspan_pd})
df_out.to_csv("tspan_eliminados.csv", index=False)