In [1]:
import os
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
# # Archivo .dat de oleaje
# nombre = "BOT1-11-T100_DAT"
# nombre_de_archivo = "BOT1-11-T100-MENSAJE3-TRIAXYSG3-NS09276-Z0-REALT-20251119-20260310-RAW.dat"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-11-T100\\DATOS"
# indices = Crear_indices_para_crudos_dat_o_txt("realt").get_indices()
# df_dat = cargar_telemetria_oleaje_dat(ruta_a_carpeta, nombre_de_archivo, indices)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [6]:
# 1.1. Cargar crudo pkl (binario + telemetría)
nombre = "BOT1-11-T100_pkl_realt_C"
archivos_csv = "msj3_crudo_unido_realt_2025111913_2026031023.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-11-T100\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-19 13:00:00  0.87  1.31  5.7  104.5    33.5
1 2025-11-19 14:00:00  0.82  1.62  5.4  106.8    34.0

In [7]:
# 1.4. Cargar datos validados (binarios + telemetría)
nombre = "BOT1-11-T80_pkl_realt_V"
nombre_de_archivo = "msj3_validados_realt_2025111913_2026031023.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-11-T100\\DATOS"
df_pkl_validados = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_validados # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_validados.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-19 13:00:00  0.87  1.31  5.7  104.5    33.5
1 2025-11-19 14:00:00  0.82  1.62  5.4  106.8    34.0

In [8]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BOT1-11-T100_NC"
nombre_de_archivo = "BOT1-11-T100-TRIAXYSG3-NS09276-Z0-REALT-20251119-20260310.nc"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\revisiones\\2026\\marzo\\BOT1-11-T100\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-19 13:00:00  0.87  1.31  5.7  104.5    33.5
1 2025-11-19 14:00:00  0.82  1.62  5.4  106.8    34.0

In [9]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-11-T100_datos_word_2025111913_2026031023.xlsx", variables="oleaje")

NAM correcto

c:\programacion\codigos_python\time_series_editor_tkinter\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:83: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

IndexError: index 129 is out of bounds for axis 2 with size 129

In [ ]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

In [ ]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)