In [1]:
import os
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
# Archivo .dat de oleaje
# nombre = "BOT1-10-T40_DAT"
# nombre_de_archivo = "BOT1-10-T40-MENSAJE4-SIG500DW-NS103996-Z0.54-REALT-20251108-20260228-RAW.dat"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-10-T40\\DATOS"
# indices = Crear_indices_para_crudos_dat_o_txt("realt").get_indices()
# df_dat = cargar_telemetria_oleaje_dat(ruta_a_carpeta, nombre_de_archivo, indices)
# dict_de_boyas[nombre] = df_dat # Guardo el dataframe dentro del diccionario de boyas.
# df_dat.head(2)

In [6]:
# # 1.1. Cargar crudo mem unido (binario mem + telemetría mem + binario realt + telemetría realt)
# nombre = "BOT1-10-T40_pkl_mem_C"
# archivos_csv = "msj3_crudo_unido_realt_2025110818_2026022823.pkl"
# ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-10-T40\\DATOS"
# df_pkl_crudo_mem = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)
# dict_de_boyas[nombre] = df_pkl_crudo_mem # Guardo el dataframe dentro del diccionario de boyas.
# df_pkl_crudo_mem.head(2)

In [7]:
# 1.2. Cargar telemetría cruda_unida .pkl (Binario + telemetría)
nombre = "BOT1-10-T40_pkl_realt_C"
nombre_de_archivo = "msj3_crudo_unido_realt_2025110818_2026022823.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-10-T40\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-08 18:00:00  0.50  0.84  3.4  78.5    35.8
1 2025-11-08 19:00:00  0.45  0.75  3.4  81.0    33.7

In [8]:
# 1.3. Cargar datos validados .pkl
nombre = "BOT1-10-T40_pkl_realt_V"
nombre_de_archivo = "msj3_validados_realt_2025110818_2026022823.pkl"
ruta_a_carpeta = "C:\\Users\\Atmosfera\\Desktop\\datos_procesados\\Revisiones\\2026\\Marzo\\BOT1-10-T40\\DATOS"
df_pkl_validados = cargar_pickle_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_validados # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_validados.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-08 18:00:00  0.50  0.84  3.4  78.5    35.8
1 2025-11-08 19:00:00  0.45  0.75  3.4  81.0    33.7

In [9]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-10-T40_NC"
nombre_de_archivo = "BOT1-10-T40-TRIAXYSG3-NS09162-Z0-REALT-20251108-20260228.nc"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2025-11-08 18:00:00  0.50  0.84  3.4  78.5    35.8
1 2025-11-08 19:00:00  0.45  0.75  3.4  81.0    33.7

In [10]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
# comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-10-T40_datos_word_2025110818_2026022823.xlsx", variables="oleaje")

NAM correcto

In [11]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BOT1-10-T40_pkl_realt_C', 'Hmax_BOT1-10-T40_pkl_realt_C',
       'Tp_BOT1-10-T40_pkl_realt_C', 'dir_BOT1-10-T40_pkl_realt_C',
       'vardir_BOT1-10-T40_pkl_realt_C', 'Hs_BOT1-10-T40_pkl_realt_V',
       'Hmax_BOT1-10-T40_pkl_realt_V', 'Tp_BOT1-10-T40_pkl_realt_V',
       'dir_BOT1-10-T40_pkl_realt_V', 'vardir_BOT1-10-T40_pkl_realt_V',
       'Hs_BOT1-10-T40_NC', 'Hmax_BOT1-10-T40_NC', 'Tp_BOT1-10-T40_NC',
       'dir_BOT1-10-T40_NC', 'vardir_BOT1-10-T40_NC'],
      dtype='str')

In [12]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)